In [1]:
from init import *

In [2]:
pd.options.display.max_columns

100

In [3]:
pd.options.display.max_columns=100

In [5]:
train_10k = pd.read_parquet("train_final_10k.parquet")

In [6]:
train_10k

,Unnamed: 0,fecha_dato,ncodpers,ind_empleado,pais_residencia,sexo,age,fecha_alta,ind_nuevo,antiguedad,indrel,ult_fec_cli_1t,indrel_1mes,tiprel_1mes,indresi,indext,conyuemp,canal_entrada,indfall,tipodom,cod_prov,nomprov,ind_actividad_cliente,renta,segmento,ind_ahor_fin_ult1,ind_aval_fin_ult1,ind_cco_fin_ult1,ind_cder_fin_ult1,ind_cno_fin_ult1,ind_ctju_fin_ult1,ind_ctma_fin_ult1,ind_ctop_fin_ult1,ind_ctpp_fin_ult1,ind_deco_fin_ult1,ind_deme_fin_ult1,ind_dela_fin_ult1,ind_ecue_fin_ult1,ind_fond_fin_ult1,ind_hip_fin_ult1,ind_plan_fin_ult1,ind_pres_fin_ult1,ind_reca_fin_ult1,ind_tjcr_fin_ult1,ind_valo_fin_ult1,ind_viv_fin_ult1,ind_nomina_ult1,ind_nom_pens_ult1,ind_recibo_ult1
0,416965,2015-01-28,15889,F,ES,V,56.0,1995-01-16,0.0,245.0,1.0,None,1.0,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0.0,0.0,0
1,836224,2015-02-28,15889,F,ES,V,56.0,1995-01-16,0.0,245.0,1.0,None,1.0,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0.0,0.0,0
2,1673961,2015-03-28,15889,F,ES,V,56.0,1995-01-16,0.0,245.0,1.0,None,1.0,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0.0,0.0,0
3,1882060,2015-04-28,15889,F,ES,V,56.0,1995-01-16,0.0,245.0,1.0,None,1.0,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0.0,0.0,0
4,3144382,2015-05-28,15889,F,ES,V,56.0,1995-01-16,0.0,245.0,1.0,None,1.0,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12715851,11931727,2016-04-28,1548202,N,ES,V,22.0,2016-04-29,1.0,0.0,1.0,None,NaN,None,S,N,None,None,N,1.0,28.0,MADRID,0.0,NaN,None,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
12715852,11931728,2016-04-28,1548203,N,ES,V,51.0,2016-04-29,1.0,0.0,1.0,None,NaN,None,S,N,None,None,N,1.0,3.0,ALICANTE,0.0,NaN,None,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
12715853,11931729,2016-04-28,1548204,N,ES,V,54.0,2016-04-29,1.0,0.0,1.0,None,NaN,None,S,N,None,None,N,1.0,8.0,BARCELONA,0.0,NaN,None,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
12715854,11931730,2016-04-28,1548206,N,ES,H,40.0,2016-04-29,1.0,0.0,1.0,None,NaN,None,S,N,None,None,N,1.0,28.0,MADRID,0.0,NaN,None,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
12715855,11931731,2016-04-28,1548207,N,ES,V,32.0,2016-04-29,1.0,0.0,1.0,None,NaN,None,S,S,None,None,N,1.0,8.0,BARCELONA,0.0,NaN,None,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0

In [20]:
non_target_cols = [i for i in train_10k.columns if not i in target_cols]
non_target_cols

['Unnamed: 0',
 'fecha_dato',
 'ncodpers',
 'ind_empleado',
 'pais_residencia',
 'sexo',
 'age',
 'fecha_alta',
 'ind_nuevo',
 'antiguedad',
 'indrel',
 'ult_fec_cli_1t',
 'indrel_1mes',
 'tiprel_1mes',
 'indresi',
 'indext',
 'conyuemp',
 'canal_entrada',
 'indfall',
 'tipodom',
 'cod_prov',
 'nomprov',
 'ind_actividad_cliente',
 'renta',
 'segmento']

In [21]:
def df2target(df,uid):
    """ 
    converts a competition data frame filteredd for a given uid into a target string 
    with the submissionformat:
    
    must return df of format
    ncodpers,added_products
    15889,ind_tjcr_fin_ult1
    15890,ind_tjcr_fin_ult1 ind_recibo_ult1
    15892,ind_nomina_ult1
    15893,
    etc.
    """
    #dfi = df.ncodpers==uid#.isin(ncodpers)
    dfi=df[df.ncodpers==uid].sort_values("fecha_dato",  ascending=True)
    #dfi.sort("fecha_dato", inplace=True, ascending=True)
    dfid=dfi[target_cols].diff(axis=0)
    df_ret = pd.concat([dfi[non_target_cols],dfid], axis=1 )
    return df_ret
    # FR: take all rows
    #dfid = dfid.iloc[-1:,:]#[dfid.fecha_dato==data_max]
    a=dfid[dfid >0].stack()#.index.tolist()
    #a=a.reset_index()["level_1"].unique().tolist()
    #a=",".join([str(uid),]+a)
    return dfid #a

In [22]:
train_10k[train_10k.ncodpers==15889]

,Unnamed: 0,fecha_dato,ncodpers,ind_empleado,pais_residencia,sexo,age,fecha_alta,ind_nuevo,antiguedad,indrel,ult_fec_cli_1t,indrel_1mes,tiprel_1mes,indresi,indext,conyuemp,canal_entrada,indfall,tipodom,cod_prov,nomprov,ind_actividad_cliente,renta,segmento,ind_ahor_fin_ult1,ind_aval_fin_ult1,ind_cco_fin_ult1,ind_cder_fin_ult1,ind_cno_fin_ult1,ind_ctju_fin_ult1,ind_ctma_fin_ult1,ind_ctop_fin_ult1,ind_ctpp_fin_ult1,ind_deco_fin_ult1,ind_deme_fin_ult1,ind_dela_fin_ult1,ind_ecue_fin_ult1,ind_fond_fin_ult1,ind_hip_fin_ult1,ind_plan_fin_ult1,ind_pres_fin_ult1,ind_reca_fin_ult1,ind_tjcr_fin_ult1,ind_valo_fin_ult1,ind_viv_fin_ult1,ind_nomina_ult1,ind_nom_pens_ult1,ind_recibo_ult1
0,416965,2015-01-28,15889,F,ES,V,56.0,1995-01-16,0.0,245.0,1.0,None,1.0,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0.0,0.0,0
1,836224,2015-02-28,15889,F,ES,V,56.0,1995-01-16,0.0,245.0,1.0,None,1.0,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0.0,0.0,0
2,1673961,2015-03-28,15889,F,ES,V,56.0,1995-01-16,0.0,245.0,1.0,None,1.0,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0.0,0.0,0
3,1882060,2015-04-28,15889,F,ES,V,56.0,1995-01-16,0.0,245.0,1.0,None,1.0,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0.0,0.0,0
4,3144382,2015-05-28,15889,F,ES,V,56.0,1995-01-16,0.0,245.0,1.0,None,1.0,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0.0,0.0,0
5,3565837,2015-06-28,15889,F,ES,V,56.0,1995-01-16,0.0,245.0,1.0,None,1.0,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0.0,0.0,0
6,4078996,2015-07-28,15889,F,ES,V,56.0,1995-01-16,0.0,245.0,1.0,None,1.0,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0.0,0.0,0
7,5319234,2015-08-28,15889,F,ES,V,56.0,1995-01-16,0.0,246.0,1.0,None,1.0,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0.0,0.0,0
8,5705188,2015-09-28,15889,F,ES,V,56.0,1995-01-16,0.0,247.0,1.0,None,1.0,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0.0,0.0,0
9,6973298,2015-10-28,15889,F,ES,V,56.0,1995-01-16,0.0,248.0,1.0,None,1.0,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0.0,0.0,0
10,7450451,2015-11-28,15889,F,ES,V,56.0,1995-01-16,0.0,249.0,1.0,None,1.0,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0.0,0.0,0
11,8617992,2015-12-28,15889,F,ES,V,56.0,1995-01-16,0.0,250.0,1.0,None,1.0,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0.0,0.0,0
12,9401570,2016-01-28,15889,F,ES,V,56.0,1995-01-16,0.0,251.0,1.0,None,1.0,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0.0,0.0,0
13,10426092,2016-02-28,15889,F,ES,V,56.0,1995-01-16,0.0,252.0,1.0,None,1.0,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0.0,0.0,0
14,11170871,2016-03-28,15889,F,ES,V,56.0,1995-01-16,0.0,253.0,1.0,None,1.0,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0.0,0.0,0
15,12221013,2016-04-28,15889,F,ES,V,56.0,1995-01-16,0.0,254.0,1.0,None,1.0,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0.0,0.0,0

In [23]:
df2target(train_10k,15889)

,Unnamed: 0,fecha_dato,ncodpers,ind_empleado,pais_residencia,sexo,age,fecha_alta,ind_nuevo,antiguedad,indrel,ult_fec_cli_1t,indrel_1mes,tiprel_1mes,indresi,indext,conyuemp,canal_entrada,indfall,tipodom,cod_prov,nomprov,ind_actividad_cliente,renta,segmento,ind_ahor_fin_ult1,ind_aval_fin_ult1,ind_cco_fin_ult1,ind_cder_fin_ult1,ind_cno_fin_ult1,ind_ctju_fin_ult1,ind_ctma_fin_ult1,ind_ctop_fin_ult1,ind_ctpp_fin_ult1,ind_deco_fin_ult1,ind_deme_fin_ult1,ind_dela_fin_ult1,ind_ecue_fin_ult1,ind_fond_fin_ult1,ind_hip_fin_ult1,ind_plan_fin_ult1,ind_pres_fin_ult1,ind_reca_fin_ult1,ind_tjcr_fin_ult1,ind_valo_fin_ult1,ind_viv_fin_ult1,ind_nomina_ult1,ind_nom_pens_ult1,ind_recibo_ult1
0,416965,2015-01-28,15889,F,ES,V,56.0,1995-01-16,0.0,245.0,1.0,None,1.0,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,836224,2015-02-28,15889,F,ES,V,56.0,1995-01-16,0.0,245.0,1.0,None,1.0,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0
2,1673961,2015-03-28,15889,F,ES,V,56.0,1995-01-16,0.0,245.0,1.0,None,1.0,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1882060,2015-04-28,15889,F,ES,V,56.0,1995-01-16,0.0,245.0,1.0,None,1.0,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,3144382,2015-05-28,15889,F,ES,V,56.0,1995-01-16,0.0,245.0,1.0,None,1.0,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
5,3565837,2015-06-28,15889,F,ES,V,56.0,1995-01-16,0.0,245.0,1.0,None,1.0,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,4078996,2015-07-28,15889,F,ES,V,56.0,1995-01-16,0.0,245.0,1.0,None,1.0,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,5319234,2015-08-28,15889,F,ES,V,56.0,1995-01-16,0.0,246.0,1.0,None,1.0,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0
8,5705188,2015-09-28,15889,F,ES,V,56.0,1995-01-16,0.0,247.0,1.0,None,1.0,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,6973298,2015-10-28,15889,F,ES,V,56.0,1995-01-16,0.0,248.0,1.0,None,1.0,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,7450451,2015-11-28,15889,F,ES,V,56.0,1995-01-16,0.0,249.0,1.0,None,1.0,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,8617992,2015-12-28,15889,F,ES,V,56.0,1995-01-16,0.0,250.0,1.0,None,1.0,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
12,9401570,2016-01-28,15889,F,ES,V,56.0,1995-01-16,0.0,251.0,1.0,None,1.0,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,10426092,2016-02-28,15889,F,ES,V,56.0,1995-01-16,0.0,252.0,1.0,None,1.0,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0
14,11170871,2016-03-28,15889,F,ES,V,56.0,1995-01-16,0.0,253.0,1.0,None,1.0,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
15,12221013,2016-04-28,15889,F,ES,V,56.0,1995-01-16,0.0,254.0,1.0,None,1.0,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0

In [18]:
train_t = []
for uid in [15889,]: # list(test_public_uid)[101:131]:
    train_t.append(df2target(train_10k, uid)) # , test.fecha_dato.max()))

In [19]:
train_t

[    ind_ahor_fin_ult1  ind_aval_fin_ult1  ind_cco_fin_ult1  ind_cder_fin_ult1  \
 0                 NaN                NaN               NaN                NaN
 1                 0.0                0.0               0.0                0.0
 2                 0.0                0.0               0.0                0.0
 3                 0.0                0.0               0.0                0.0
 4                 0.0                0.0               0.0                0.0
 5                 0.0                0.0               0.0                0.0
 6                 0.0                0.0               0.0                0.0
 7                 0.0                0.0               0.0                0.0
 8                 0.0                0.0               0.0                0.0
 9                 0.0                0.0               0.0                0.0
 10                0.0                0.0               0.0                0.0
 11                0.0                0.0               0.0                0.0
 12                0.0                0.0               0.0                0.0
 13                0.0                0.0               0.0                0.0
 14                0.0                0.0               0.0                0.0
 15                0.0                0.0               0.0                0.0

     ind_cno_fin_ult1  ind_ctju_fin_ult1  ind_ctma_fin_ult1  ind_ctop_fin_ult1  \
 0                NaN                NaN                NaN                NaN
 1                0.0                0.0                0.0                0.0
 2                0.0                0.0                0.0                0.0
 3                0.0                0.0                0.0                0.0
 4                0.0                0.0                0.0                0.0
 5                0.0                0.0                0.0                0.0
 6                0.0                0.0                0.0                0.0
 7                0.0                0.0                0.0                0.0
 8                0.0                0.0                0.0                0.0
 9                0.0                0.0                0.0                0.0
 10               0.0                0.0                0.0                0.0
 11               0.0                0.0                0.0                0.0
 12               0.0                0.0                0.0                0.0
 13               0.0                0.0                0.0                0.0
 14               0.0                0.0                0.0                0.0
 15               0.0                0.0                0.0                0.0

     ind_ctpp_fin_ult1  ind_deco_fin_ult1  ind_deme_fin_ult1  \
 0                 NaN                NaN                NaN
 1                 0.0                0.0                0.0
 2                 0.0                0.0                0.0
 3                 0.0                0.0                0.0
 4                 0.0                0.0                0.0
 5                 0.0                0.0                0.0
 6                 0.0                0.0                0.0
 7                 0.0                0.0                0.0
 8                 0.0                0.0                0.0
 9                 0.0                0.0                0.0
 10                0.0                0.0                0.0
 11                0.0                0.0                0.0
 12                0.0                0.0                0.0
 13                0.0                0.0                0.0
 14                0.0                0.0                0.0
 15                0.0                0.0                0.0

     ind_dela_fin_ult1  ind_ecue_fin_ult1  ind_fond_fin_ult1  ind_hip_fin_ult1  \
 0                 NaN                NaN                NaN               NaN
 1                 0.0                0.0                0.0               0.0
 2                 0.0                0.0                0.0               0.0
 3                 0.0                0.0                0.0               0.0
 4                 0.0                0.0                0.0               0.0
 5                 0.0                0.0                0.0               0.0
 6                 0.0                0.0                0.0               0.0
 7                 0.0                0.0                0.0               0.0
 8                 0.0                0.0                0.0               0.0
 9                 0.0                0.0                0.0               0.0
 10                0.0                0.0                0.0               0.0
 11                0.0                0.0                0.0               0.0
 12                0.0                0.0                0.0               0.0
 13                0.0                0.0                0.0               0.0
 14                0.0                0.0                0.0               0.0
 15                0.0                0.0                0.0               0.0

     ind_plan_fin_ult1  ind_pres_fin_ult1  ind_reca_fin_ult1  \
 0                 NaN                NaN                NaN
 1                 0.0                0.0                0.0
 2                 0.0                0.0                0.0
 3                 0.0                0.0                0.0
 4                 0.0                0.0                0.0
 5                 0.0                0.0                0.0
 6                 0.0                0.0                0.0
 7                 0.0                0.0                0.0
 8                 0.0                0.0                0.0
 9                 0.0                0.0                0.0
 10                0.0                0.0                0.0
 11                0.0                0.0                0.0
 12                0.0                0.0                0.0
 13                0.0                0.0                0.0
 14                0.0                0.0                0.0
 15                0.0                0.0                0.0

     ind_tjcr_fin_ult1  ind_valo_fin_ult1  ind_viv_fin_ult1  ind_nomina_ult1  \
 0                 NaN                NaN               NaN              NaN
 1                -1.0                0.0               0.0              0.0
 2                 0.0                0.0               0.0              0.0
 3                 0.0                0.0               0.0              0.0
 4                 1.0                0.0               0.0              0.0
 5                 0.0                0.0               0.0              0.0
 6                 0.0                0.0               0.0              0.0
 7                -1.0                0.0               0.0              0.0
 8                 0.0                0.0               0.0              0.0
 9                 0.0                0.0               0.0              0.0
 10                0.0                0.0               0.0              0.0
 11                1.0                0.0               0.0              0.0
 12                0.0                0.0               0.0              0.0
 13               -1.0                0.0               0.0              0.0
 14                1.0                0.0               0.0              0.0
 15               -1.0                0.0               0.0              0.0

     ind_nom_pens_ult1  ind_recibo_ult1
 0                 NaN              NaN
 1                 0.0              0.0
 2                 0.0              0.0
 3                 0.0              0.0
 4                 0.0              0.0
 5                 0.0              0.0
 6                 0.0              0.0
 7                 0.0              0.0
 8                 0.0              0.0
 9                 0.0              0.0
 10                0.0              0.0
 11                0.0              0.0
 12                0.0              0.0
 13                0.0              0.0
 14                0.0              0.0
 15                0.0              0.0  ]

In [ ]:
- apply to all uid 
- get value_counts: how many churn and buy cases in each column
-